const express = require('express')
const app = express()
const login = require('./login')
const user = require('./user')
const post = require('./post')
const comment = require('./comment')
const like = require('./like')
const mes = require('./mes')
const search = require('./search')
app.use('/post', express.static('post'))
app.use(login)
app.use(user)
app.use(post)
app.use(like)
app.use(comment)
app.use(mes)
app.use(search)
app.listen(8083, () => {
    console.log('run server');
})